### ISSUE TITLE
Use compilerArgs rather than deprecated compilerArguments in examples/.../parent

### ISSUE THREAD

**Issue by kwin** [lastnpe/eclipse-null-eea-augments#11]
In https://github.com/lastnpe/eclipse-null-eea-augments/blob/master/examples/maven/parent/pom.xml#L52 the new configuration property `compilerArgs` should be used instead of the deprecated `compilerArguments` (https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#compilerArgs).

**Comment by vorburger** [comment]
This should not be done before https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/issues/11 is implemented...

**Comment by sebthom** [comment]
> This should not be done before [lastnpe/eclipse-external-annotations-m2e-plugin#11](https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/issues/11) is implemented...

@vorburger hmm, I changed it as part of https://github.com/lastnpe/eclipse-null-eea-augments/commit/5b59e61cca73600872d625e8578dce90c977d46a

**Comment by vorburger** [comment]
Indeed, I can see you've used `compilerArgs`.

In that case, I guess this is moot, as it's done; I'll close it. 

PS: You're very welcome to close outdated issues yourself as well in the future, if you like!
