### ISSUE TITLE
Regarding Optional.orElse

### ISSUE THREAD

**Issue by vimil** [lastnpe/eclipse-null-eea-augments#127]
with eclipse external annotations on Optional I see the below signature
**@Nonnull** String **@Nonnull** java.util.Optional.orElse(**@Nullable** String other)
shouldn't this be 
**@Nullable** String **@Nonnull** java.util.Optional.orElse(**@Nullable** String other)

instead, as the javadoc for orElse states that the return type can be null if in the input parameter is null

**Comment by J-N-K** [comment]
Correct
