### ISSUE TITLE
System.out probably should not be @Nullable

### ISSUE THREAD

**Issue by agentgt** [lastnpe/eclipse-null-eea-augments#137]
System.out being nullable is painful.

It is indeed nullable but in practice it is rarely.

**Comment by agentgt** [comment]
I suppose one could argue don't use system.out but we do for unit tests where slf4j isn't worth importing.

**Comment by J-N-K** [comment]
I agree that this is very unfortunatey (as is @Nullable on `Optional.orElse`) but I don't think we should add technically incorrect annotations. because it is more convenient. 

In unit tests you can probably work around that with a single 

```
private static final PrintStream SYSTEM_OUT = Objects.requireNonNull(System.out);
```

**Comment by agentgt** [comment]
Yeah I totally agree. I for some reason thought it was very rare but looking at the code its entirely possible and its better to be exact for contracts.
