### ISSUE TITLE
Collectors toList/toSet/toCollection should have a return value of Nonnull

### ISSUE THREAD

**Issue by agentgt** [lastnpe/eclipse-null-eea-augments#138]
It appears the Collectors.eaa file is incorrect.

That is `Collectors.toSet()` and `Collectors.toList()` are reported as `@Nullable`.

Original toSet:

```
toSet
 <T:Ljava/lang/Object;>()Ljava/util/stream/Collector<TT;*Ljava/util/Set<TT;>;>;
 <T:Ljava/lang/Object;>()Ljava/util/stream/Collector<TT;*L1java/util/Set<TT;>;>;
```

Should be marked as `L1`

```
toSet
 <T:Ljava/lang/Object;>()Ljava/util/stream/Collector<TT;*Ljava/util/Set<TT;>;>;
 <T:Ljava/lang/Object;>()L1java/util/stream/Collector<TT;*L1java/util/Set<TT;>;>
                                        // ^^--- I guess this is the return value

```

I'm still learning the format of EEA so perhaps this is wrong but regardless my code inspection of toList/toSet to not be possible for it to return null.

**Comment by J-N-K** [comment]
Correct, Could you prepare a PR for that? I think that `toCollection` also results in a non-null `Collector` and requires a non-null `Supplier`.
