### ISSUE TITLE
Automated deployment of master SNAPSHOT builds (central or Bintray)

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-null-eea-augments#14]
It would probably be useful if the latest bleeding edge SNAPSHOT EEA could be automatically deploy from master to Maven central or at least Bintray after every merge.

**Comment by maggu2810** [comment]
Hm, this aren't snapshot repositories. Or which one do you mean?

**Comment by vorburger** [comment]
@maggu2810 you're probably right, Maven central could not host lastpne.org SNAPSHOT... But e.g. Bintray.com personal repos (not the same as their jCentral) could host SNAPSHOT, AFAIK.

Full disclosure: My motivation to provide this (or not) will mainly be driven by https://bugs.opendaylight.org/show_bug.cgi?id=9170.

**Comment by kaikreuzer** [comment]
@maggu2810 is right, Bintray is only meant for releases, not for snapshots - I already had some complaints by their staff when I accidentially misused it once ;-)

BUT: JFrog has a heart for us poor developers and so they offer oss.jfrog.io, see https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org.
This is directly used through Bintray - so if you use Bintray as a deploy target for the Maven build, it will automatically redirect snapshots to Artifactory (if your project has been approved for it).

**Comment by vorburger** [comment]
I'm closing this issue because I think the next focus should now be on https://github.com/lastnpe/eclipse-null-eea-augments/issues/29 (some time, whenever), which is about regularly releasing (monthly?), but non SNAPSHOT, instead of the idea we discussed here (for SNAPSHOT).

This conclusion is partly based on discussions I've meanwhile had in https://bugs.opendaylight.org/show_bug.cgi?id=9170 with people with I work in another community (opendaylight.org), where we amicably concluded that SNAPSHOT dependencies are not what we'll want to consume, there.

PS: Should anyone else reading this have any interest in SNAPSHOT releasing lastnpe.org artifacts after all, and is willing to do the respective work (admin, build scripts, documenting, support etc.), then I would not want to stand in your way - just comment here, and we'll re-open the issue and you can do what you think must be done!
