### ISSUE TITLE
Invite agentgt@ as committer and co-maintainer

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-null-eea-augments#165]
In https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/issues/51, the @agentgt wrote:

> I have been meaning to talk to @vorburger about joining the lastnpe org and helping out more including fixing this plugin.

@agentgt I'm (very) happy to have you here! I've just sent you an invite which grants you committer privilege, should you accept it? (You'll need 2FA enabled.)

Please resolve this issue to ACK - or comment if you need any other privileges or anything else.

PS: Similar to past #91 and #75 (and #16).

**Comment by vorburger** [comment]
Pro Memoria: @agentgt tentatively expressed interest over in https://github.com/lastnpe/eclipse-null-eea-augments/issues/166#issuecomment-2297445040.

**Comment by agentgt** [comment]
@vorburger this is embarrassing as I'm not sure what happened to the invite. It has been a little bit since I have joined a github org and they must have changed the process.

Is it an email or is there something else?

**Comment by agentgt** [comment]
@vorburger Sorry I finally got the invite. I'm not sure what happened but it wasn't showing up earlier. I'll follow up in a week and start working on lastnpe.

Cheers

**Comment by J-N-K** [comment]
Maybe it was lost, I did send it again some hours ago.
