### ISSUE TITLE
Invite sebthom@ as committer and co-maintainer (if still ⏳  interested? 😄) 

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-null-eea-augments#166]
@sebthom to follow-up on https://github.com/lastnpe/eclipse-null-eea-augments/issues/16#issuecomment-1473761661, with only 1.5 years delay 😄 :

Just in case you are still interested,  I've just sent you an invite which grants you committer privilege! (You'll need 2FA enabled.)

Please resolve this issue to ACK - or comment if you need any other privileges or anything else.

FYI @agentgt re. #165.

**Comment by agentgt** [comment]
I’m on vacation today but will follow up later this week!

**Comment by sebthom** [comment]
@vorburger  I didn't receive an invite.

**Comment by vorburger** [comment]
> I’m on vacation today but will follow up later this week!

@agentgt yours is #165; this one is for @sebthom! 🤣 

> @vorburger I didn't receive an invite.

@sebthom I could have sworn that I had pressed the button yesterday, but indeed you were not showing up on _Pending_ today... not sure what happened there, but anyway, NOW you should have received it? Sorry for the confusion!
