### ISSUE TITLE
How to get rid of Travis Check ?!?

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-null-eea-augments#184]
Even though the other day I had [removed the Travis "App" in the Settings of this repo](https://github.com/lastnpe/eclipse-null-eea-augments/settings/installations),

even on a brand new PR clearly created AFTER that, such as my #183 from just now, there is STILL a:

> Travis CI - Pull Request Expected — Waiting for status to be reported

How do I get rid of that?!

**Comment by J-N-K** [comment]
In the "Branch protection rules" as a requirement. I removed it.
