### ISSUE TITLE
Suffix EEA library modules with major version?

### ISSUE THREAD

**Issue by sebthom** [lastnpe/eclipse-null-eea-augments#192]
To be able to support multiple major versions of some libraries in the future, they must be configured in separate maven modules.

In [no-npe](https://github.com/vegardit/no-npe/tree/main/libs) it e.g. looks like this:
```
eea-byte-buddy-1
eea-classgraph-4
eea-commons-configuration-2
eea-commons-io-2
eea-commons-lang-3
eea-directory-watcher-0
eea-eclipse-platform
eea-gson-2
eea-guava
eea-jackson-2
eea-jakarta-mail-api-2
eea-jakarta-servlet-api-6
eea-java-11
eea-java-17
eea-java-21
eea-javax-mail-api-1
eea-javax-portlet-api-3
eea-javax-servlet-api-4
eea-jaxb-4
eea-junit-5
eea-osgi-core-8
eea-quartz-2
eea-slf4j-1
eea-slf4j-2
eea-snakeyaml-2
eea-spring-5
eea-spring-6
eea-wicket-10
eea-xstream-1
```

Should we do something like this for [lastnpe](https://github.com/lastnpe/eclipse-null-eea-augments/tree/main/libraries) too?

My suggestion:
|current name|suggested name|comment
|-|-|-
guava|guava| no name change too many frequent releases
javamail|javax-mail-api-1|I will later add jakarta-mail-api-2 from no-npe
jetty|jetty-client-12
mockito|mockito-5
osgi-core|osgi-core-8
servlet-api|javax-servlet-api-4|I will later add jakarta-servlet-api-6 from no-npe
slf4j-api|slf4j-api-1|I will later add slf4j-api-2 from no-npe
spring|spring-5|do we want to continue supporting spring 5<br> or should we directly move to spring 6?
xstream|xstream-1

@vorburger  @J-N-K

**Comment by vorburger** [comment]
Versioning like this SGTM.

As for Spring 5 / 6 support, do whatever YOU need! 😹
