### ISSUE TITLE
154 eea files

### ISSUE THREAD

**Issue by numeralnathan** [lastnpe/eclipse-null-eea-augments#48]
Here are 154 eea files.  Enjoy!

[External Annotations.zip](https://github.com/lastnpe/eclipse-null-eea-augments/files/1403571/External.Annotations.zip)

**Comment by sylvainlaurent** [comment]
could you create one or several pull requests?
thanks

**Comment by vorburger** [comment]
@nathanila OMG, wow - thanks a lot! This is the biggest lot so far, so I'm (mostly) "just curious" - where are these from? Auto. gen. by some tooling, or hand written? By yourself or someone else, who gave you permission to contribute it to this project? If you have the time to create a real PR for us instead of attaching a ZIP, that would be great just for "traceability" in Git of who contributed what when how...

**Comment by nathanila** [comment]
I wrote a tool that reads the class file and outputs the eea lines without the 0 or 1 notations.  I then go back through the Java source code and add the 0 or 1 notations.  This makes it much faster to get to the final version of the eea.

I created these eea files over the past year or so.

Every time I make file an issue on github, everyone asks me to create a PR.  Every time I think, "I do not know how and I do not want to take the time to figure it out."  It is probably painfully easy to do.

**Comment by vorburger** [comment]
@nathanila Thanks for the clarification. I gather that these are created by you alone (not based on other annotation metadata which could have had had an incomptible license, not taken from anywhere), and that by uploading your ZIP here to this issue you are proposing them for inclusion in this project. So no problem from my side for any other contributor to just take your ZIP and make a PR from it - if you cannot?

But we encourage you to learn more about Git and GitHub PRs - it's a great collaboration tool and will "unlock" you to be able to more actively directly participate in many open source communities - which is lots of fun and rewarding! In case you are interested and want to pursue but need a starting point, here are some useful pointers:

* https://try.github.io
* https://guides.github.com
* https://help.github.com/articles/creating-a-pull-request/

PS: Re. a tool, I've had some ideas that I think are somewhat similar to what you have probably done, see our discussion on https://github.com/lastnpe/eclipse-null-eea-augments/issues/16 and my (so far empty) shell project on https://github.com/lastnpe/external-annotations-esperanto .. let us know if you want to join the party and help out more based on your experience with this!

**Comment by nathanila** [comment]
I created these eea files.  There are no incompatible licenses.  I am proposing these eea files for including in this project.  I have no problem with any one to just take my ZIP and make a PR from it.

**Comment by vorburger** [comment]
Closing this as we're now getting this in via https://github.com/lastnpe/eclipse-null-eea-augments/pull/56 - thanks to @Bananeweizen !

**Comment by vorburger** [comment]
Actually hang on - the #56 only takes the EEA for JDK from this ZIP, right? There's more in it - any takers?

slf4j, Jackson, Apache HTTP Client, Glassfish HTTP, Freemarker, JSoup.

**Comment by Bananeweizen** [comment]
I can convert those too. However, I will only be able to do some real testing and review on slfj and Freemarker, since I'm not using the other libraries.

**Comment by sebthom** [comment]
We now have a more comprehensive set of EEAs for slf4j and Jackson incorporated.
