### ISSUE TITLE
Single Maven artifact (JAR) with ALL EEAs

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-null-eea-augments#51]
https://github.com/lastnpe/eclipse-null-eea-augments/issues/29#issuecomment-342519347 has raised the idea of producing a single Maven artifact (JAR) with ALL of the EEAs from the different folders in this repo.

I think what would be both quite easy to do and probably a useful extension in general for some people who prefer single instead of many small per library artifacts.

You could just introduce a new Maven POM artifact in this project, like say an `org.lastnpe.eea:all-eea`, which using some appropriate Maven plugin... either some fancy überjar thingie, or probably this can be done somehow with the [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/) ?

Actually making the latest build of that artifact available on a URL is out of scope of this issue, and is either https://github.com/lastnpe/eclipse-null-eea-augments/issues/29 for non-SNAPSHOT or (revive) https://github.com/lastnpe/eclipse-null-eea-augments/issues/14, if there is any interest.

PR for this would be welcome.. @triller-telekom perhaps you would like to contribute this? :smiley_cat:

**Comment by vorburger** [comment]
@triller-telekom are you OK to close this issue one now, following the merge of PR https://github.com/lastnpe/eclipse-null-eea-augments/pull/57 ?

**Comment by triller-telekom** [comment]
I think what is still missing is the publication of the accumulated artifact to maven central. Do you like to open another issue for that or do you want to keep this open until it is done?

Who has published the other artifacts to maven central? Was it you? Maybe you can then also publish that one. Afterwards this issue can be closed.

**Comment by vorburger** [comment]
@triller-telekom actually making the latest build of that artifact available on a URL is out of scope of this issue, and is either #29 (@ctron was going to take that on..) for non-SNAPSHOT or (revive) #14, if there is any interest.

**Comment by triller-telekom** [comment]
#29 is definitely what this project should have some time. But until that reviving #14 would be nice if someone has a jfrog account and experience how to publish an maven artifact. Because we still have little annotations in here it would be nice to test with bleeding edge versions until we are at a point where we have tons of annotations and can wait for the next (monthly?) release. WDYT?
