### ISSUE TITLE
Discussion: Eclipse IDE Java projects + external annotations

### ISSUE THREAD

**Issue by triller-telekom** [lastnpe/eclipse-null-eea-augments#58]
I am opening this issue as a discussion on how one could implement support for projects of type "Java project" within the Eclipse IDE.

As briefly mentioned in https://github.com/lastnpe/eclipse-null-eea-augments/issues/52#issuecomment-343253148 the plugin [eclipse-external-annotations-m2e-plugin](https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin) is only for "Maven projects" within the Eclipse IDE.

Since the Eclipse JDT compiler is able to read the external annotations via its special "-annotationpath CLASSPATH" if you run it on the console, I am wondering how the eclipse-external-annotations-m2e-plugin makes use of it.

The GUI of the Eclipse IDE itself does not allow inserting "CLASSPATH" as a value in the projects build path on where it can find the external annotations.

So I am wondering if anyone has an idea on how to tell the jdt compiler within the IDE to read its external annotations fro the CLASSPATH?

**Comment by sebthom** [comment]
Nowadays Eclipse has the option "Search for external annotations in all build path locations" ![image](https://github.com/user-attachments/assets/8d719ea5-1046-46ac-8895-5a7c58d4e3bf)
