### ISSUE TITLE
Discussion: Do we really need to properly version EEA, and if so, how would you like to?

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-null-eea-augments#60]
We haven't had the need to give much thought really re. properly version-ing EEA JARs... the way we currently have, it is just: Single version (in the Maven GAV sense) for all EEA as currently in this repo, perhaps [even timestamp type versions discussed in the regular release issue](https://github.com/lastnpe/eclipse-null-eea-augments/issues/29), and not a per-library specific version.

I always thought that should be just fine, because I don't really see JDK, Guava, slf4j & Co. ever doing API incompatible changes which would require different EEA for different versions of those libraries - but maybe that's a bit overly optimistic, in the long run?

If someone disagree with this admitedly a bit simplistic view, then let's discuss here... or, always better than words to discuss, just start proposing PR with changes to make this stuff more version aware!

If someone is really motivated to pick this up, I guess we could [start adding something OSGi like version ranges into the eea-for-gav files after the G:A](https://github.com/lastnpe/eclipse-null-eea-augments/blob/master/libraries/slf4j-api/)? And then have [our eclipse-external-annotations-m2e-plugin](https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin) be a bit smarter than it is today, and read such versions, and iff present (backwards compatible) find the EEA, correctly interpreting and matching the version range? I guess it's certainly doable... but a bit of work - more than I personally have time to sink into, right now.

**Comment by maggu2810** [comment]
Why not using the GAV of the upstream / annotated project and a classifier "eea"?

**Comment by vorburger** [comment]
> Why not using the GAV of the upstream / annotated project and a classifier "eea"?

We should and cannot not release say `org.guava` from `LastNPE.org` to Maven central.

Equally importantly, even if we still used `org.lastnpe` as G, wouldn't this then require us to have N `libraries/` each with a POM for the respective upstream annotated GAV ? I'm not too keen on instead of say the current [libraries/guava](https://github.com/lastnpe/eclipse-null-eea-augments/tree/master/libraries/guava) us all having to keep maintaining `libraries/guava-23.4-jre`, `libraries/guava-23.3-jre`, `libraries/guava-23.2-jre`, `libraries/guava-23.0` ... etc. from http://repo1.maven.org/maven2/com/google/guava/guava/ when, I suspect, the EEA will _usually_ be _mostly_ always the same, for all of these...

So IMHO you would want/need some sort of version range support.. Maven also has that of course, not just OSGi. Or can you think of some neat trick / simpler way which I'm perhaps missing how we could do this anyway? The eclipse-external-annotations-m2e-plugin needs to be worked on for this - which I'm all for, if you want to go for it... :smile:

**Comment by maggu2810** [comment]
> We should and cannot not release say `org.guava` from `LastNPE.org` to Maven central.

That is correct. I missed that above.

The best approach would be to create PRs to the upstream project so their API already contains the nullness annotations. Perhaps the Eclipse tooling could support different annotation namespaces as well.
As long as the projects does not contain the annotations we should perhaps think about version ranges. I agree.

**Comment by sylvainlaurent** [comment]
We can also stand still and see if a real need appears...

**Comment by jftsunami** [comment]
There is a need with packages being removed from JSE (Jaxb for example)

**Comment by J-N-K** [comment]
In anpther discussion we agreed that there is no need for explicit versioning. Closing here. If an acrual problem arises from not having explicit versioning, please open a new issue.
