### ISSUE TITLE
Welcome rPraml as commiter (if he's interested)

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-null-eea-augments#75]
based on https://github.com/lastnpe/eclipse-null-eea-augments/commits?author=rPraml, @rPraml now qualifies for what's outlined on https://github.com/lastnpe/eclipse-null-eea-augments#contribute : _"Anyone making 3 intelligent contributions to this repo may ask to be promoted from a contributor to a committer with full write access."_

@rPraml are you interested in getting commit write privileges here?

**Comment by rPraml** [comment]
Hello Michael, thanks for the invitation. Of course I'm interested ;)

**Comment by vorburger** [comment]
@rPraml you should have just received an invite? You need to have your GitHub account secured with 2FA.

**Comment by vorburger** [comment]
@rPraml I just noticed that you have meanwhile accepted that invite - welcome! Please do feel free to self merge things in this project, such as e.g. your #77, if none of the other committers (including me) get around to review.

One small thing - you could change your membership in the lastnpe GitHub org to public?
