### ISSUE TITLE
Shouldn't isInstance be able to handle null parameter?

### ISSUE THREAD

**Issue by FluBBaOfWard** [lastnpe/eclipse-null-eea-augments#84]
https://github.com/lastnpe/eclipse-null-eea-augments/blob/d22045f5167246fb985d2c3512ca573ffb4d2fc2/libraries/java/java/lang/Class.eea#L151
isInstanceOf is used all the time to do null checks shouldn't this also be able to handle that?

**Comment by maggu2810** [comment]
I agree, `isInstance` handles null arguments.

Also the documentation states:

> The method returns true if the specified Object argument is non-null and can be cast to the reference type represented by this Class object without raising a ClassCastException. It returns false otherwise.

**Comment by FluBBaOfWard** [comment]
Thank you for the quick response!

**Comment by vorburger** [comment]
@FluBBaOfWard @maggu2810 so does the .eea need a PR from one of you to be adapted, or OK as is?

**Comment by maggu2810** [comment]
I assume `L0` would be "more correct" then `L1`.
