### ISSUE TITLE
Invite @jason-faust and @J-N-K as committers

### ISSUE THREAD

**Issue by vorburger** [lastnpe/eclipse-null-eea-augments#91]
@jason-faust and @J-N-K in #85 seem to show interest in this project - great!

Personally I'm currently not in a position to maintain this project. Other committers (@sylvainlaurent @kaikreuzer @maggu2810 @brychcy @ctron @rPraml #75 @victornoel) don't seem to be either anymore?

Ergo, and inspired by https://github.com/lastnpe/eclipse-null-eea-augments#contribute, the responsible open source stewardship thing for the last person to do in such situations is to invite both @jason-faust and @J-N-K as committers so that they can maintain this project!

I've just sent you invites via GitHub, which you can Accept, or Decline. You will require to have 2FA enabled. This issue can be used to discuss anything related to it. Please close it yourselves after you've concluded this.

Welcome - and best of luck with maintaining this project! :smiling_imp:

**Comment by maggu2810** [comment]
> Personally I'm currently not in a position to maintain this project. Other committers (@sylvainlaurent @kaikreuzer @maggu2810 @brychcy @ctron @rPraml #75 @victornoel) don't seem to be either anymore?

Same is true for me, too.

**Comment by jason-faust** [comment]
Sure, I can help out a bit. On weekends mostly but I'd love to get this up and functional again.

**Comment by ctron** [comment]
> Personally I'm currently not in a position to maintain this project. Other committers (@sylvainlaurent @kaikreuzer @maggu2810 @brychcy @ctron @rPraml #75 @victornoel) don't seem to be either anymore?

Same here. I don't run into many NPEs when working with Rust :grin:

**Comment by vorburger** [comment]
@J-N-K @jason-faust just an FYI that I've just "unwatched" this repo now, seeing that it is I great hands with you! If you still need me for anything in the future, please raise/tag me @vorburger, as I won't be actively "reading along" anymore, as I have do far. Just wanted to let you know. Thanks again for stepping up and in here. This, to me, is open source at its best. All the best to you.
