### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by J-N-K** [lastnpe/eclipse-null-eea-augments#94]
While #29 is about regular releases (and should be addressed) I would like to discuss the next release independently from that. 

There are two main things to discuss:

1. version
2. release process

Regarding 1:

#92 suggest different versions for JDK8/11, this seems to be a good idea, but I have to idea how to solve that short-term. Since the current code (after #93 )  targets JDK11 I would suggest to focus on a JDK11-release. Since we still have semver-versioning, I would we should increase the version to 2.0.0 and keep that for all artifacts. . I would then suggest to go on with 2.1.0-SNAPSHOT afterwards. 

Regarding 2:

I can prepare a PR to increase the version to what ever we decide in (1), do the release build, and a second PR for the next development version. What needs to be figured out is how the release can be uploaded to Maven Central. I have only done releases to bintray in the past.

**Comment by vorburger** [comment]
> What needs to be figured out is how the release can be uploaded to Maven Central. 

follow https://central.sonatype.org/pages/ossrh-guide.html

If you tell them that you are a commiter to org.lastnpe, they should grant it to you (normally; shout here if problems).

**Comment by maggu2810** [comment]
If we ever think about different releases for different JDK versions - perhaps version 11.0 would make sense... Or you use classifiers...

**Comment by J-N-K** [comment]
@maggu2810 After thinking about it, the JDK version is only relevant for the tests (they fail if a method is not available). Having annotations for non-existing methods will not lead to problems when using the EEA. The only problem would be if different annotations would be neede for the same method for different JDK versions. AFAIK this is not the case.

**Comment by J-N-K** [comment]
@vorburger I guess the person needed is you: https://issues.sonatype.org/plugins/servlet/mobile#issue/OSSRH-61141/comment/973905

**Comment by vorburger** [comment]
> @vorburger I guess the person needed is you

done - commented on https://issues.sonatype.org/browse/OSSRH-61141, as requested.

Thank You for pushing forward here - it's always great to see this kind of "continuity" in open source!

**Comment by J-N-K** [comment]
If no one vetoes, I would merge #97 next weekend and do the 2.0.0 release immediately after that. We would continue with 2.1.0-SNAPSHOT afterwards.

**Comment by vorburger** [comment]
> If no one vetoes, I would merge #97 next weekend and do the 2.0.0 release immediately after that.

I very much doubt anyone would veto, and as the current active maintainer, encourage you to just push ahead as you see fit - that's totally fair.
