### ISSUE TITLE
Is there some reason that /libraries/java/java/util/stream/Stream.eea does not cover "collect()"?

### ISSUE THREAD

**Issue by davidmichaelkarr** [lastnpe/eclipse-null-eea-augments#98]
I'm just starting to explore this, but my initial experiments didn't quite work, and it appears that it might be because the "collect()" function isn't covered. Is this just an oversight, or is there a technical reason why "collect()" can't be handled here?

**Comment by jason-faust** [comment]
The Stream class is barely annotated at this time. only methods that have annotations assigned is filter() and map()

**Comment by davidmichaelkarr** [comment]
I can see that. That's why I asked the question. Can someone answer that question?

**Comment by jason-faust** [comment]
There is no technical reason. It just wasn't done. A lot of the existing classes have been annotated 'as needed', and the collect() method was not annotated at the start of the Stream class.
